repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff
        args: [--fix]
        additional_dependencies: []

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: ["-ll", "-r", "."]
        pass_filenames: false
        language_version: python3.12

  - repo: https://github.com/kalaverin/radon
    rev: 0.2.1
    hooks:
      - id: radon
        args: ["--warn-time=120", "--error-effort=2000"]
        language_version: python3.12